//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid Id { get; set; }
        public System.Guid User1 { get; set; }
        public System.Guid User2 { get; set; }
    
        public virtual User FirstUser { get; set; }
        public virtual User SecondUser { get; set; }
    }
}
